#!/bin/sh 
#PBS -S /bin/bash
#PBS -q batch
#PBS -l nodes=1:ppn=6
#PBS -N mapping-757
#PBS -l walltime=60:00:00
#PBS -o mapping-757.out
#PBS -e mapping-757.err
#PBS -l mem=100gb
 
 
module load cutadapt
module load pigz
ulimit -c unlimited
cd $TMPDIR
wget https://www.dropbox.com/s/smzofp758ny3l5f/757-2699_S5_L001_R1_001.fastq.gz?dl=0 -O 757-2699_S5_L001_R1_001.fastq.gz
wget https://www.dropbox.com/s/a4895jflbxxnyux/757-2699_S5_L001_R2_001.fastq.gz?dl=0 -O 757-2699_S5_L001_R2_001.fastq.gz
wget https://www.dropbox.com/s/p5cqwvu9ivh3ffu/757-2699_S5_L002_R1_001.fastq.gz?dl=0 -O 757-2699_S5_L002_R1_001.fastq.gz
wget https://www.dropbox.com/s/187wt9zhyhkij7g/757-2699_S5_L002_R2_001.fastq.gz?dl=0 -O 757-2699_S5_L002_R2_001.fastq.gz
wget https://www.dropbox.com/s/gb7wil81ri3slos/757-2699_S5_L003_R1_001.fastq.gz?dl=0 -O 757-2699_S5_L003_R1_001.fastq.gz
wget https://www.dropbox.com/s/5c1zlpmsltneku6/757-2699_S5_L003_R2_001.fastq.gz?dl=0 -O 757-2699_S5_L003_R2_001.fastq.gz
wget https://www.dropbox.com/s/722a45nlmd8o75x/757-2699_S5_L004_R1_001.fastq.gz?dl=0 -O 757-2699_S5_L004_R1_001.fastq.gz
wget https://www.dropbox.com/s/y1p4cafu988c28v/757-2699_S5_L004_R2_001.fastq.gz?dl=0 -O 757-2699_S5_L004_R2_001.fastq.gz
 
cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -q 30,30 -o 757-2699_S5_L001_R1_001.fastq_trimmed.fastq.gz -p 757-2699_S5_L001_R2_001.fastq_trimmed.fastq.gz  757-2699_S5_L001_R1_001.fastq.gz 757-2699_S5_L001_R2_001.fastq.gz 
cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -q 30,30 -o 757-2699_S5_L002_R1_001.fastq_trimmed.fastq.gz -p 757-2699_S5_L002_R2_001.fastq_trimmed.fastq.gz  757-2699_S5_L002_R1_001.fastq.gz 757-2699_S5_L002_R2_001.fastq.gz 
cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -q 30,30 -o 757-2699_S5_L003_R1_001.fastq_trimmed.fastq.gz -p 757-2699_S5_L003_R2_001.fastq_trimmed.fastq.gz  757-2699_S5_L003_R1_001.fastq.gz 757-2699_S5_L003_R2_001.fastq.gz 
cutadapt -a AGATCGGAAGAGC -A AGATCGGAAGAGC -q 30,30 -o 757-2699_S5_L004_R1_001.fastq_trimmed.fastq.gz -p 757-2699_S5_L004_R2_001.fastq_trimmed.fastq.gz  757-2699_S5_L004_R1_001.fastq.gz 757-2699_S5_L004_R2_001.fastq.gz 
 
module load SAMtools
module load BWA
module load BCFtools
module load VCFtools
module load GATK/3.8-0-Java-1.8.0_144
module load picard/2.21.6-Java-11
module load Java/1.8.0_92
 
bwa mem -t 6 -M /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -R  "@RG\tLB:Lib1\tID:1\tSM:757\tPL:ILLUMINA" $TMPDIR/757-2699_S5_L001_R1_001.fastq_trimmed.fastq.gz  $TMPDIR/757-2699_S5_L001_R2_001.fastq_trimmed.fastq.gz  > $TMPDIR/757_1.sam
samtools sort $TMPDIR/757_1.sam -o $TMPDIR/757_1.bam
samtools index $TMPDIR/757_1.bam
bwa mem -t 6 -M /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -R  "@RG\tLB:Lib1\tID:1\tSM:757\tPL:ILLUMINA" $TMPDIR/757-2699_S5_L002_R1_001.fastq_trimmed.fastq.gz  $TMPDIR/757-2699_S5_L002_R2_001.fastq_trimmed.fastq.gz  > $TMPDIR/757_2.sam
samtools sort $TMPDIR/757_2.sam -o $TMPDIR/757_2.bam
samtools index $TMPDIR/757_2.bam
bwa mem -t 6 -M /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -R  "@RG\tLB:Lib1\tID:1\tSM:757\tPL:ILLUMINA" $TMPDIR/757-2699_S5_L003_R1_001.fastq_trimmed.fastq.gz  $TMPDIR/757-2699_S5_L003_R2_001.fastq_trimmed.fastq.gz  > $TMPDIR/757_3.sam
samtools sort $TMPDIR/757_3.sam -o $TMPDIR/757_3.bam
samtools index $TMPDIR/757_3.bam
bwa mem -t 6 -M /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -R  "@RG\tLB:Lib1\tID:1\tSM:757\tPL:ILLUMINA" $TMPDIR/757-2699_S5_L004_R1_001.fastq_trimmed.fastq.gz  $TMPDIR/757-2699_S5_L004_R2_001.fastq_trimmed.fastq.gz  > $TMPDIR/757_4.sam
samtools sort $TMPDIR/757_4.sam -o $TMPDIR/757_4.bam
samtools index $TMPDIR/757_4.bam
java -Xmx32g -jar /usr/local/apps/eb/picard/2.21.6-Java-11/picard.jar MarkDuplicates INPUT=$TMPDIR/757_1.bam OUTPUT=$TMPDIR/757_1.bam.dedup.bam METRICS_FILE=$TMPDIR/757_1.bam.metrics REMOVE_DUPLICATES=true ASSUME_SORTED=true VALIDATION_STRINGENCY=LENIENT
java -Xmx32g -jar /usr/local/apps/eb/picard/2.21.6-Java-11/picard.jar MarkDuplicates INPUT=$TMPDIR/757_2.bam OUTPUT=$TMPDIR/757_2.bam.dedup.bam METRICS_FILE=$TMPDIR/757_2.bam.metrics REMOVE_DUPLICATES=true ASSUME_SORTED=true VALIDATION_STRINGENCY=LENIENT
java -Xmx32g -jar /usr/local/apps/eb/picard/2.21.6-Java-11/picard.jar MarkDuplicates INPUT=$TMPDIR/757_3.bam OUTPUT=$TMPDIR/757_3.bam.dedup.bam METRICS_FILE=$TMPDIR/757_3.bam.metrics REMOVE_DUPLICATES=true ASSUME_SORTED=true VALIDATION_STRINGENCY=LENIENT
java -Xmx32g -jar /usr/local/apps/eb/picard/2.21.6-Java-11/picard.jar MarkDuplicates INPUT=$TMPDIR/757_4.bam OUTPUT=$TMPDIR/757_4.bam.dedup.bam METRICS_FILE=$TMPDIR/757_4.bam.metrics REMOVE_DUPLICATES=true ASSUME_SORTED=true VALIDATION_STRINGENCY=LENIENT
samtools merge -cf $TMPDIR/757.bam.dedup.bam $TMPDIR/757_1.bam.dedup.bam $TMPDIR/757_2.bam.dedup.bam $TMPDIR/757_3.bam.dedup.bam $TMPDIR/757_4.bam.dedup.bam
samtools index $TMPDIR/757.bam.dedup.bam
java -Xmx32g -jar $EBROOTGATK/GenomeAnalysisTK.jar -I $TMPDIR/757.bam.dedup.bam -R /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -T RealignerTargetCreator -o $TMPDIR/757.intervals
java -jar $EBROOTGATK/GenomeAnalysisTK.jar -I $TMPDIR/757.bam.dedup.bam -R /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -T IndelRealigner --filter_bases_not_stored -o /scratch/vt20265/bam_files/757.realign.bam -targetIntervals $TMPDIR/757.intervals
java -Xmx30g -jar $EBROOTGATK/GenomeAnalysisTK.jar -T BaseRecalibrator -I /scratch/vt20265/bam_files/757.realign.bam -R /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -o /scratch/vt20265/bam_files/757.bam.dedup.realign.calibration.csv -knownSites /scratch/vt20265/bam_files/known.vcf.gz
java -Xmx30g -jar $EBROOTGATK/GenomeAnalysisTK.jar -T PrintReads -I /scratch/vt20265/bam_files/757.realign.bam -R /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -BQSR /scratch/vt20265/bam_files/757.bam.dedup.realign.calibration.csv -o /scratch/vt20265/bam_files/757.final.bam
samtools flagstat /scratch/vt20265/bam_files/757.final.bam > /scratch/vt20265/bam_files/757.flagstat
#java -Xmx30g -jar  $EBROOTGATK/GenomeAnalysisTK.jar -T HaplotypeCaller -R /work/smalab/Venkat/genome/Danaus_plexippus_v3_-_scaffolds.fa -I /scratch/vt20265/bam_files/757.final.bam --emitRefConfidence GVCF  -o /scratch/vt20265/bam_files/757.final.bam.g.vcf
